options:
  lineNumbers: true
  spellcheck: true
  askImageFilename: true
  imagePath: /image
  imagePrefix: 2020_03_29_01_
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: true
